baseURL = "https://longj724.github.io/"
languageCode = "en-us"
title = "Home"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "longj724.github.io"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Justin Long"
    info = "Student at the University of Michigan"
    description = "Justin Long's personal website"
    keywords = "computer science,developer,university of michigan,software,"
    avatarurl = "images/avatar-3.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x github"
    weight = 1
    url = "https://github.com/longj724/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x twitter"
    weight = 3
    url = "https://twitter.com/justin21long/"
  [[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin-in fa-2x linkedin"
    weight = 3
    url = "https://linkedin.com/in/justin-long-97493218a"

# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
